maintainer        'Gábor Vészi'
maintainer_email  'veszig@done.hu'
license           'Apache 2.0'
description       'Sets up /etc/portage and defines portage functions'
version           '0.1'
supports          'gentoo'
