maintainer       "Gábor Vészi"
maintainer_email "veszig@done.hu"
license          "Apache 2.0"
description      "Installs and configures syslog-ng"
version          "0.1"
supports         "gentoo"
depends          "gentoo"
