maintainer       "Gábor Vészi"
maintainer_email "veszig@done.hu"
license          "Apache 2.0"
description      "Installs and configures iptables"
version          "0.1"
recipe           "iptables::ulogd", "Installs ulogd"
supports         "gentoo"
